// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVuESJ0jqvmQGB53RlleirzQTxqlxnrIY',
    appId: '1:42604232188:web:b443610a5db45847f58679',
    messagingSenderId: '42604232188',
    projectId: 'notes-a17de',
    authDomain: 'notes-a17de.firebaseapp.com',
    databaseURL: 'https://notes-a17de-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'notes-a17de.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQ3gexy_yR6fP5EWHXHAeN09Lao1CUrYE',
    appId: '1:42604232188:android:f48984c91fbb6e10f58679',
    messagingSenderId: '42604232188',
    projectId: 'notes-a17de',
    databaseURL: 'https://notes-a17de-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'notes-a17de.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdcc43hUVPp-YCAd8pxMUOlSFHBeftK9g',
    appId: '1:42604232188:ios:40bc61bea8cec001f58679',
    messagingSenderId: '42604232188',
    projectId: 'notes-a17de',
    databaseURL: 'https://notes-a17de-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'notes-a17de.appspot.com',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdcc43hUVPp-YCAd8pxMUOlSFHBeftK9g',
    appId: '1:42604232188:ios:40bc61bea8cec001f58679',
    messagingSenderId: '42604232188',
    projectId: 'notes-a17de',
    databaseURL: 'https://notes-a17de-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'notes-a17de.appspot.com',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVuESJ0jqvmQGB53RlleirzQTxqlxnrIY',
    appId: '1:42604232188:web:69100c699ed90e61f58679',
    messagingSenderId: '42604232188',
    projectId: 'notes-a17de',
    authDomain: 'notes-a17de.firebaseapp.com',
    databaseURL: 'https://notes-a17de-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'notes-a17de.appspot.com',
  );

}